"""remove useless columns from tasks table

Revision ID: e2d7db071bae
Revises: 51865bb59b0b
Create Date: 2025-03-21 19:51:02.169492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2d7db071bae'
down_revision = '51865bb59b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('input_from')
        batch_op.drop_column('output_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_from', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('output_to', sa.String(length=255), nullable=False, server_default=''))

    # ### end Alembic commands ###
