"""Added column errors in table tasks

Revision ID: e356713d739b
Revises: e2d7db071bae
Create Date: 2025-05-12 10:41:48.806499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e356713d739b'
down_revision = 'e2d7db071bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('errors', sa.String(length=128), nullable=False), insert_after='result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('errors')
    # ### end Alembic commands ###
