"""Create tasks table

Revision ID: 51865bb59b0b
Revises:
Create Date: 2025-03-20 18:33:16.008163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51865bb59b0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
        sa.Column('id', sa.INTEGER(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('uuid', sa.String(length=128), nullable=False, server_default=''),
        sa.Column('file_id', sa.String(length=128), nullable=False, server_default=''),
        sa.Column('file_url', sa.String(length=2048), nullable=False, server_default=''),
        sa.Column('finetune_args', sa.String(length=2048), nullable=False, server_default=''),
        sa.Column('callback_url', sa.String(length=2048), nullable=False, server_default=''),
        sa.Column('input_from', sa.String(length=255), nullable=False, server_default=''),
        sa.Column('output_to', sa.String(length=255), nullable=False, server_default=''),
        sa.Column('tarball_location', sa.String(length=2048), nullable=False, server_default=''),
        sa.Column('tarball_checksum', sa.String(length=255), nullable=False, server_default=''),
        sa.Column('status', sa.String(length=32), nullable=False, server_default=''),
        sa.Column('result', sa.String(length=32), nullable=False, server_default=''),
        sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None),
        sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None),
        sa.PrimaryKeyConstraint('id'),
        sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
