"""Added table bearers

Revision ID: 69151d88848f
Revises: e356713d739b
Create Date: 2026-01-29 09:52:46.349557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69151d88848f'
down_revision = 'e356713d739b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bearers',
        sa.Column('id', sa.INTEGER(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('owner', sa.String(length=128), nullable=False, server_default=''),
        sa.Column('token', sa.String(length=128), nullable=False, server_default=''),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, server_default=None),
        sa.PrimaryKeyConstraint('id'),
        sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bearers')
    # ### end Alembic commands ###
