"""Added column labels to table bearers

Revision ID: c976427dbc52
Revises: 69151d88848f
Create Date: 2026-01-29 12:10:13.713844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c976427dbc52'
down_revision = '69151d88848f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bearers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labels', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bearers', schema=None) as batch_op:
        batch_op.drop_column('labels')
    # ### end Alembic commands ###
